services:

  beyla:
    image: grafana/beyla:latest
    pid: "host"
    privileged: true
    environment:
      BEYLA_TRACE_PRINTER: text
      BEYLA_OPEN_PORT: 80
      BEYLA_PROMETHEUS_PORT: 9090
      OTEL_EXPORTER_OTLP_ENDPOINT: http://<alloy-ip>:4317
